### ISSUE TITLE
multiple paths are not allowed

### ISSUE THREAD

**Issue by yegor256** [g4s8/xcop-action#3]
I would like to have an ability to do this:

```
- uses: g4s8/xcop-action@master
  with:
    license: MY_LICENSE.txt
    files: "src/*.xml"
```

and this:

```
- uses: g4s8/xcop-action@master
  with:
    license: MY_LICENSE.txt
    files: 
      - "src/*.xml"
      - "src/*.xsl"
```

At the moment, the second option is not possible.
